import { Client } from "./types";

export const data: Client[] = [
  {
    id: "C7D9E2A1-B3F5",
    clientName: "Sarah Johnson",
    medicalStatus: "Stable - Outpatient Care",
    lawFirm: "Anderson & Associates LLP",
    doa: "2023-08-15",
    caseStatus: "Active",
    paymentMethod: "Insurance",
    amount: 12500.0,
    dateOfBirth: "1985-03-22",
    expenses: [
      {
        label: "Initial Medical Evaluation",
        amount: 2500.0,
        deductedFrom: "Insurance",
      },
      {
        label: "Physical Therapy Sessions",
        amount: 1800.0,
        deductedFrom: "Insurance",
      },
      {
        label: "Legal Documentation",
        amount: 750.0,
        deductedFrom: "Direct Payment",
      },
    ],
  },
  {
    id: "F8B2E4C6-A9D1",
    clientName: "Michael Rodriguez",
    medicalStatus: "Recovering",
    lawFirm: "Thompson & Baker Law",
    doa: "2023-11-30",
    caseStatus: "Pending",
    paymentMethod: "Direct Payment",
    amount: 8750.0,
    dateOfBirth: "1992-07-14",
    expenses: [
      {
        label: "Emergency Room Visit",
        amount: 3200.0,
        deductedFrom: "Direct Payment",
      },
      {
        label: "Medical Reports",
        amount: 450.0,
        deductedFrom: "Direct Payment",
      },
    ],
  },
  {
    id: "A1C3E5G7-H9B2",
    clientName: "Emily Chen",
    medicalStatus: "Critical",
    lawFirm: "Wilson Legal Group",
    doa: "2024-01-05",
    caseStatus: "Urgent",
    paymentMethod: "Medicare",
    amount: 25000.0,
    dateOfBirth: "1978-11-03",
    expenses: [
      {
        label: "Initial Medical Evaluation",
        amount: 2500.0,
        deductedFrom: "Insurance",
      },
    ],
  },
  {
    id: "K4M6N8P0-Q2S4",
    clientName: "David Smith",
    medicalStatus: "Stable",
    lawFirm: "Johnson & Johnson Law",
    doa: "2023-09-22",
    caseStatus: "Resolved",
    paymentMethod: "Insurance",
    amount: 15750.0,
    dateOfBirth: "1990-05-18",
    expenses: [
      {
        label: "Initial Medical Evaluation",
        amount: 2500.0,
        deductedFrom: "Insurance",
      },
    ],
  },
  {
    id: "T5V7X9Y1-Z3B5",
    clientName: "Lisa Brown",
    medicalStatus: "Under Observation",
    lawFirm: "Martinez Legal Services",
    doa: "2023-12-10",
    caseStatus: "Active",
    paymentMethod: "Self-Pay",
    amount: 9800.0,
    dateOfBirth: "1982-09-30",
    expenses: [
      {
        label: "Initial Medical Evaluation",
        amount: 2500.0,
        deductedFrom: "Insurance",
      },
    ],
  },
  {
    id: "C4D6E8F0-G2H4",
    clientName: "James Wilson",
    medicalStatus: "Discharged",
    lawFirm: "Cohen & Associates",
    doa: "2023-10-05",
    caseStatus: "Closed",
    paymentMethod: "Insurance",
    amount: 18200.0,
    dateOfBirth: "1975-12-15",
    expenses: [
      {
        label: "Initial Medical Evaluation",
        amount: 2500.0,
        deductedFrom: "Insurance",
      },
    ],
  },
  {
    id: "J6K8L0M2-N4P6",
    clientName: "Maria Garcia",
    medicalStatus: "Intensive Care",
    lawFirm: "Peterson Law Group",
    doa: "2024-02-01",
    caseStatus: "Critical",
    paymentMethod: "Medicaid",
    amount: 32000.0,
    dateOfBirth: "1988-04-25",
    expenses: [
      {
        label: "Initial Medical Evaluation",
        amount: 2500.0,
        deductedFrom: "Insurance",
      },
      {
        label: "Initial Medical Evaluation",
        amount: 2500.0,
        deductedFrom: "Insurance",
      },
      {
        label: "Initial Medical Evaluation",
        amount: 2500.0,
        deductedFrom: "Insurance",
      },
    ],
  },
  {
    id: "Q8R0S2T4-U6W8",
    clientName: "Robert Taylor",
    medicalStatus: "Stable",
    lawFirm: "Williams & Wright",
    doa: "2023-11-15",
    caseStatus: "Active",
    paymentMethod: "Insurance",
    amount: 14500.0,
    dateOfBirth: "1995-08-07",
    expenses: [
      {
        label: "Initial Medical Evaluation",
        amount: 2500.0,
        deductedFrom: "Insurance",
      },
    ],
  },
  {
    id: "X0Y2Z4A6-B8C0",
    clientName: "Jennifer Lee",
    medicalStatus: "Recovery",
    lawFirm: "Davis Legal Solutions",
    doa: "2023-12-20",
    caseStatus: "Pending",
    paymentMethod: "Direct Payment",
    amount: 11300.0,
    dateOfBirth: "1987-01-12",
    expenses: [
      {
        label: "Initial Medical Evaluation",
        amount: 2500.0,
        deductedFrom: "Insurance",
      },
    ],
  },
  {
    id: "D2E4F6G8-H0J2",
    clientName: "William Anderson",
    medicalStatus: "Stable",
    lawFirm: "Smith & Partners",
    doa: "2023-09-08",
    caseStatus: "Active",
    paymentMethod: "Insurance",
    amount: 16800.0,
    dateOfBirth: "1980-06-28",
    expenses: [
      {
        label: "Initial Medical Evaluation",
        amount: 2500.0,
        deductedFrom: "Insurance",
      },
    ],
  },
  {
    id: "K4L6M8N0-P2Q4",
    clientName: "Patricia Martinez",
    medicalStatus: "Outpatient",
    lawFirm: "Brown & Associates",
    doa: "2024-01-15",
    caseStatus: "Active",
    paymentMethod: "Medicare",
    amount: 9500.0,
    dateOfBirth: "1973-10-09",
    expenses: [
      {
        label: "Initial Medical Evaluation",
        amount: 2500.0,
        deductedFrom: "Insurance",
      },
    ],
  },
  {
    id: "R6S8T0U2-V4W6",
    clientName: "Thomas White",
    medicalStatus: "Critical",
    lawFirm: "Garcia Law Firm",
    doa: "2023-12-05",
    caseStatus: "Urgent",
    paymentMethod: "Insurance",
    amount: 28500.0,
    dateOfBirth: "1993-02-14",
    expenses: [
      {
        label: "Initial Medical Evaluation",
        amount: 2500.0,
        deductedFrom: "Insurance",
      },
    ],
  },
  {
    id: "X8Y0Z2A4-B6C8",
    clientName: "Susan Miller",
    medicalStatus: "Stable",
    lawFirm: "Taylor & Taylor",
    doa: "2023-10-25",
    caseStatus: "Resolved",
    paymentMethod: "Self-Pay",
    amount: 13200.0,
    dateOfBirth: "1984-07-31",
    expenses: [
      {
        label: "Initial Medical Evaluation",
        amount: 2500.0,
        deductedFrom: "Insurance",
      },
    ],
  },
  {
    id: "D0E2F4G6-H8J0",
    clientName: "Kevin Jones",
    medicalStatus: "Under Treatment",
    lawFirm: "Wilson & Associates",
    doa: "2024-02-10",
    caseStatus: "Active",
    paymentMethod: "Insurance",
    amount: 19700.0,
    dateOfBirth: "1991-12-03",
    expenses: [
      {
        label: "Initial Medical Evaluation",
        amount: 2500.0,
        deductedFrom: "Insurance",
      },
    ],
  },
  {
    id: "K2L4M6N8-P0Q2",
    clientName: "Michelle Thompson",
    medicalStatus: "Recovering",
    lawFirm: "Lee Legal Group",
    doa: "2023-11-01",
    caseStatus: "Pending",
    paymentMethod: "Medicaid",
    amount: 21000.0,
    dateOfBirth: "1976-05-17",
    expenses: [
      {
        label: "Initial Medical Evaluation",
        amount: 2500.0,
        deductedFrom: "Insurance",
      },
    ],
  },
  {
    id: "R4S6T8U0-V2W4",
    clientName: "Christopher Davis",
    medicalStatus: "Stable",
    lawFirm: "Anderson Law Firm",
    doa: "2023-12-15",
    caseStatus: "Active",
    paymentMethod: "Insurance",
    amount: 17500.0,
    dateOfBirth: "1989-08-22",
    expenses: [
      {
        label: "Surgery",
        amount: 8500.0,
        deductedFrom: "Insurance",
      },
      {
        label: "Post-operative Care",
        amount: 2200.0,
        deductedFrom: "Insurance",
      },
      {
        label: "Legal Consultation",
        amount: 1500.0,
        deductedFrom: "Direct Payment",
      },
    ],
  },
];
